apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-postgres-pvc
  namespace: task-management
  labels:
    app: task-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
